version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.compose*"
      androidx:
        patterns:
          - "androidx.*"
      koin:
        patterns:
          - "io.insert-koin*"
      supabase:
        patterns:
          - "io.github.jan-tennert.supabase*"
