package io.github.b150005.skeinly.config

import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * Phase 39.2: smoke-tests the Android actual generated by
 * `generateBuildFlagsAndroid` from `version.properties`.
 *
 * Since the generated actual is a build-time constant (compiled from the
 * `VERSION_NAME` `-beta` suffix detection at build time, not runtime),
 * test stability is tied to whatever `version.properties` says when the
 * test compiles. Today `VERSION_NAME=1.0.0-beta1` so `isBeta == true` is
 * the load-bearing assertion. When v1.0.0 GA ships and the suffix drops,
 * this test must flip to `assertFalse(BuildFlags.isBeta)` in the same
 * commit that bumps `version.properties` — the failing CI is the
 * intentional reminder that the iOS `iosApp/project.yml` `IS_BETA: "YES"`
 * setting must also be flipped (it has no codegen path). See the COUPLED
 * EDIT note in `version.properties`.
 */
class BuildFlagsTest {
    @Test
    fun isBeta_matches_versionProperties_suffix() {
        // version.properties currently declares VERSION_NAME=1.0.0-beta1,
        // so the codegen-derived actual must be true. Phase 40 GA bump
        // will flip both this assertion and version.properties together.
        assertTrue(BuildFlags.isBeta, "BuildFlags.isBeta should be true while version.properties carries -beta")
    }
}
