package io.github.b150005.skeinly.domain.model

import kotlin.time.Instant

/**
 * Phase 25.1 (ADR-024) — friendship state in the [FriendConnection]
 * lifecycle. Closed enum so `when` statements stay exhaustive.
 *
 * Wire constants match the `state` CHECK on `public.friend_connections`
 * (migration 035): `pending` / `accepted` / `blocked`.
 */
enum class FriendConnectionState(
    val wireValue: String,
) {
    Pending("pending"),
    Accepted("accepted"),
    Blocked("blocked"),
    ;

    companion object {
        fun fromWire(value: String): FriendConnectionState =
            entries.firstOrNull { it.wireValue == value }
                ?: error("Unknown FriendConnectionState wire value: $value")
    }
}

/**
 * Phase 25.1 (ADR-024) — one edge of the mutual-confirmation friendship
 * graph. Composite key on sorted `(userA, userB)`; the application
 * layer is responsible for sorting before INSERT.
 *
 * **From the caller's perspective**, the "other user" is whichever of
 * [userA] / [userB] is NOT the caller's auth.uid(). Helper:
 * [otherUserId].
 *
 * [requesterId] is the sender of the original friend request. For
 * pending requests, the receiver (whoever isn't the requester) is the
 * one who can transition state to `accepted`.
 *
 * [acceptedAt] is non-null IFF [state] == `Accepted` per the DB CHECK
 * constraint `friend_connections_accepted_at_matches_state`.
 */
data class FriendConnection(
    val userA: String,
    val userB: String,
    val state: FriendConnectionState,
    val requesterId: String,
    val createdAt: Instant,
    val acceptedAt: Instant?,
) {
    /**
     * Returns the participant who is NOT [callerId]. Used by UI to
     * render "your friend X" from a friend_connections row without
     * caring which side of the pair the caller is on.
     *
     * Throws if [callerId] is not a participant — this is a contract
     * violation by the caller (they should not be asking about an
     * edge they're not part of).
     */
    fun otherUserId(callerId: String): String =
        when (callerId) {
            userA -> userB
            userB -> userA
            else ->
                error(
                    "callerId $callerId is not a participant in this edge ($userA, $userB)",
                )
        }

    /**
     * True when [callerId] sent the original request. Used to render
     * "you sent" vs "they sent" in the Pending tab.
     */
    fun callerIsRequester(callerId: String): Boolean = requesterId == callerId
}

/**
 * Phase 25.1 (ADR-024) — single-use 14-day invite. Generated by
 * `create_friend_invite()` RPC (migration 036).
 *
 * The client surfaces [code] to the user for paste-text invitations
 * and [token] to the OS share sheet for Universal Link invitations
 * (path `/skeinly/friend/<token>`).
 *
 * [consumedAt] is non-null IFF [consumedBy] is non-null per the DB
 * CHECK `friend_invites_consumed_pair`. An invite is "outstanding"
 * when both are null AND [expiresAt] > now.
 */
data class FriendInvite(
    val id: String,
    val token: String,
    val code: String,
    val expiresAt: Instant,
    val consumedAt: Instant?,
    val consumedBy: String?,
    val createdAt: Instant,
) {
    /** True when the invite has neither been consumed nor expired. */
    fun isOutstanding(now: Instant): Boolean = consumedAt == null && expiresAt > now
}
