import java.io.FileInputStream
import java.util.Properties

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.androidKmpLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.sqldelight)
    alias(libs.plugins.kover)
}

val localProps =
    Properties().also { props ->
        val localFile = rootProject.file("local.properties")
        if (localFile.exists()) props.load(FileInputStream(localFile))
        // CI fallback: read from environment variables when local.properties is absent
        System.getenv("SUPABASE_URL")?.let { props.setProperty("SUPABASE_URL", it) }
        System.getenv("SUPABASE_PUBLISHABLE_KEY")?.let { props.setProperty("SUPABASE_PUBLISHABLE_KEY", it) }
    }

val generateSupabaseConfig by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/supabaseConfig")
    val url = localProps.getProperty("SUPABASE_URL", "")
    val key = localProps.getProperty("SUPABASE_PUBLISHABLE_KEY", "")
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.resolve("io/github/b150005/skeinly/config")
        dir.mkdirs()
        val escapedUrl = url.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        val escapedKey = key.replace("\\", "\\\\").replace("\"", "\\\"").replace("$", "\\$")
        dir.resolve("SupabaseCredentials.kt").writeText(
            buildString {
                appendLine("package io.github.b150005.skeinly.config")
                appendLine()
                appendLine("internal object SupabaseCredentials {")
                appendLine("    const val URL: String = \"$escapedUrl\"")
                appendLine("    const val PUBLISHABLE_KEY: String = \"$escapedKey\"")
                appendLine("}")
            },
        )
    }
}

// Phase 39.2: derive `BuildFlags.isBeta` for shared/androidMain from
// `version.properties` `VERSION_NAME`. Beta builds carry semver
// `0.X.Y` (major == 0 = pre-stable API); v1.0 GA bumps the major
// component to 1 (per agent-team deliberation 2026-05-05; see
// `version.properties` header for the full rationale). Codegen pattern
// mirrors `generateSupabaseConfig` because the AGP 9.x KMP plugin
// (`com.android.kotlin.multiplatform.library`) does not expose the
// standard `buildFeatures { buildConfig = true }` knob to shared android
// source sets, so `BuildConfig.IS_BETA` is unavailable here. The iOS
// actual reads from Info.plist at runtime — see `BuildFlags.ios.kt` and
// `iosApp/project.yml`'s `IS_BETA` setting.
//
// Defensive default: malformed/missing VERSION_NAME → major defaults to
// 0 → isBeta = true. Failing safe (treat unknown as beta) avoids
// accidentally shipping a "production" binary if a parser regression
// or upstream config error blanks the version string.
val versionProps =
    Properties().also { props ->
        val versionFile = rootProject.file("version.properties")
        if (versionFile.exists()) props.load(FileInputStream(versionFile))
    }

val generateBuildFlagsAndroid by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildFlags")
    val versionName = versionProps.getProperty("VERSION_NAME", "")
    val major = versionName.substringBefore('.').toIntOrNull() ?: 0
    val isBeta = major == 0
    outputs.dir(outputDir)
    inputs.property("isBeta", isBeta)
    doLast {
        val dir = outputDir.get().asFile.resolve("io/github/b150005/skeinly/config")
        dir.mkdirs()
        dir.resolve("BuildFlags.android.kt").writeText(
            buildString {
                appendLine("package io.github.b150005.skeinly.config")
                appendLine()
                appendLine("/** Generated by `generateBuildFlagsAndroid` from version.properties. */")
                appendLine("actual object BuildFlags {")
                appendLine("    actual val isBeta: Boolean = $isBeta")
                appendLine("}")
            },
        )
    }
}

kotlin {
    applyDefaultHierarchyTemplate()

    compilerOptions {
        // Suppress KT-61573 Beta warning for expect/actual classes — the
        // feature is stable in practice and our KMP architecture relies on
        // expect/actual class hierarchies (DriverFactory, ConnectivityMonitor,
        // SupabaseConfig, ImagePicker). Tracked upstream for stabilization.
        freeCompilerArgs.add("-Xexpect-actual-classes")
    }

    android {
        namespace = "io.github.b150005.skeinly.shared"
        compileSdk = 36
        minSdk = 26

        withHostTestBuilder {}.configure {}

        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation(libs.kotlinx.coroutines.core)
            implementation(libs.kotlinx.datetime)
            implementation(libs.kotlinx.serialization.json)
            implementation(libs.koin.core)
            implementation(libs.koin.compose)
            implementation(libs.koin.compose.viewmodel)
            implementation(libs.sqldelight.runtime)
            implementation(libs.sqldelight.coroutines)
            implementation(libs.androidx.lifecycle.viewmodel)
            implementation(libs.androidx.lifecycle.runtime.compose)
            implementation(libs.navigation.compose)
            implementation(compose.material3)
            implementation(compose.materialIconsExtended)
            implementation(compose.foundation)
            implementation(compose.ui)
            implementation(compose.components.resources)
            // Supabase
            implementation(project.dependencies.platform(libs.supabase.bom))
            implementation(libs.supabase.auth)
            implementation(libs.supabase.postgrest)
            implementation(libs.supabase.compose.auth)
            implementation(libs.supabase.compose.auth.ui)
            implementation(libs.supabase.realtime)
            implementation(libs.supabase.storage)
            implementation(libs.supabase.functions)
            // Image loading
            implementation(libs.coil.compose)
            implementation(libs.coil.network.ktor)
            // Preferences
            implementation(libs.multiplatform.settings)
        }
        commonTest.dependencies {
            implementation(libs.kotlin.test)
            implementation(libs.kotlinx.coroutines.test)
            implementation(libs.turbine)
        }
        androidMain {
            kotlin.srcDir(
                generateSupabaseConfig.flatMap {
                    layout.buildDirectory.dir("generated/supabaseConfig")
                },
            )
            kotlin.srcDir(
                generateBuildFlagsAndroid.flatMap {
                    layout.buildDirectory.dir("generated/buildFlags")
                },
            )
            dependencies {
                implementation(libs.koin.android)
                implementation(libs.sqldelight.android.driver)
                implementation(libs.ktor.client.android)
                implementation(libs.multiplatform.settings.no.arg)
                // Required for androidx.activity.compose.BackHandler used by
                // ui/platform/SystemBackHandler.android.kt
                implementation(libs.androidx.activity.compose)
            }
        }
        getByName("androidHostTest") {
            dependencies {
                implementation(libs.sqldelight.sqlite.driver)
            }
        }
        iosMain.dependencies {
            implementation(libs.sqldelight.native.driver)
            implementation(libs.ktor.client.darwin)
            implementation(libs.multiplatform.settings.no.arg)
        }
        iosTest.dependencies {
            implementation(libs.sqldelight.native.driver)
        }
    }
}

// Ensure the generated SupabaseCredentials + BuildFlags sources are available
// before any task that consumes the androidMain source set. The flatMap-based
// srcDir wiring should carry the task dependency, but the AGP 9.x KMP plugin
// does not propagate it to compile or ktlint tasks on CI (Gradle 9.x
// implicit-dependency validation catches this).
tasks.configureEach {
    if (name.contains("AndroidMain", ignoreCase = true)) {
        dependsOn(generateSupabaseConfig)
        dependsOn(generateBuildFlagsAndroid)
    }
}

// Wire root-defined verifyI18nKeys task into :shared:check so the pre-push
// invariant chain (./gradlew :shared:check) automatically covers i18n key
// parity. Path-based reference (":verifyI18nKeys") is configuration-cache
// safe — equivalent to the rootProject.tasks lookup but evaluated lazily.
tasks.named("check") {
    dependsOn(":verifyI18nKeys")
}

sqldelight {
    databases {
        create("SkeinlyDatabase") {
            packageName.set("io.github.b150005.skeinly.db")
        }
    }
}

compose.resources {
    // Explicit package so common-module consumers get a stable import path
    // (`io.github.b150005.skeinly.generated.resources.Res`). Without this
    // the package is derived from the module name and can shift if we rename
    // `shared`. `publicResClass` exposes `Res` to platform modules that embed
    // the framework (androidApp, iosApp).
    publicResClass = true
    packageOfResClass = "io.github.b150005.skeinly.generated.resources"
    generateResClass = always
}

kover {
    reports {
        filters {
            excludes {
                classes(
                    // Generated / infra
                    "io.github.b150005.skeinly.db.*",
                    "io.github.b150005.skeinly.di.*",
                    "io.github.b150005.skeinly.ui.navigation.*",
                    "io.github.b150005.skeinly.config.*",
                    // Generated by org.jetbrains.compose.components.resources
                    // — the `Res` class and per-key accessors are static
                    // lookup plumbing with no behavior worth covering.
                    "io.github.b150005.skeinly.generated.resources.*",
                    // Remote data sources — thin Supabase SDK wrappers, untestable without MockEngine.
                    // Security validation (auth, input sanitization, size limits) is covered at the UseCase layer.
                    "io.github.b150005.skeinly.data.remote.Remote*DataSource",
                    "io.github.b150005.skeinly.data.remote.SupabaseConfig",
                    "io.github.b150005.skeinly.data.remote.SupabaseConfigKt",
                    "io.github.b150005.skeinly.data.remote.ConnectivityMonitor",
                    // Compose UI — untestable on JVM (covered by Android instrumented tests)
                    "*.ComposableSingletons\$*",
                    "io.github.b150005.skeinly.ui.chartviewer.*",
                    "io.github.b150005.skeinly.ui.imagepicker.*",
                    "io.github.b150005.skeinly.ui.activityfeed.ActivityFeedScreenKt*",
                    "io.github.b150005.skeinly.ui.auth.LoginScreenKt*",
                    "io.github.b150005.skeinly.ui.discovery.DiscoveryScreenKt*",
                    "io.github.b150005.skeinly.ui.comments.CommentSectionKt*",
                    "io.github.b150005.skeinly.ui.profile.ProfileScreenKt*",
                    "io.github.b150005.skeinly.ui.projectdetail.ProjectDetailScreenKt*",
                    "io.github.b150005.skeinly.ui.projectdetail.ShareLinkDialogKt*",
                    "io.github.b150005.skeinly.ui.projectdetail.UserPickerDialogKt*",
                    "io.github.b150005.skeinly.ui.projectlist.CreateProjectDialogKt*",
                    "io.github.b150005.skeinly.ui.projectlist.ProjectListScreenKt*",
                    "io.github.b150005.skeinly.ui.sharedcontent.SharedContentScreenKt*",
                    "io.github.b150005.skeinly.ui.sharedwithme.SharedWithMeScreenKt*",
                    "io.github.b150005.skeinly.ui.patternlibrary.PatternLibraryScreenKt*",
                    "io.github.b150005.skeinly.ui.patternedit.PatternEditScreenKt*",
                    "io.github.b150005.skeinly.ui.settings.SettingsScreenKt*",
                    "io.github.b150005.skeinly.ui.onboarding.OnboardingScreenKt*",
                    "io.github.b150005.skeinly.ui.components.EmptyStateViewKt*",
                    "io.github.b150005.skeinly.ui.symbol.SymbolGalleryScreenKt*",
                    "io.github.b150005.skeinly.ui.chart.ChartViewerScreenKt*",
                    "io.github.b150005.skeinly.ui.chart.ChartEditorScreenKt*",
                    "io.github.b150005.skeinly.ui.chart.ChartHistoryScreenKt*",
                    "io.github.b150005.skeinly.ui.chart.ChartDiffScreenKt*",
                    "io.github.b150005.skeinly.ui.chart.ChartBranchPickerSheetKt*",
                    "io.github.b150005.skeinly.ui.chart.SymbolDrawingKt*",
                    "io.github.b150005.skeinly.ui.chart.PolarDrawingKt*",
                    "io.github.b150005.skeinly.ui.chart.ChartThumbnailKt*",
                    "io.github.b150005.skeinly.ui.pullrequest.PullRequestListScreenKt*",
                    "io.github.b150005.skeinly.ui.pullrequest.PullRequestDetailScreenKt*",
                    "io.github.b150005.skeinly.ui.pullrequest.ChartConflictResolutionScreenKt*",
                    "io.github.b150005.skeinly.ui.platform.*",
                )
            }
        }
        verify {
            rule {
                minBound(80)
            }
        }
    }
}

// Phase 41.1.4: regenerate `symbol-packs/<pack_id>/<version>/payload.json`
// for the seed packs (`jis.knit.beginner` + `jis.crochet.beginner`) by
// running the always-on `SymbolPackPayloadGeneratorTest` test with the
// `skeinly.payloads.outputDir` system property set. The test asserts pack
// invariants on every CI run; setting the system property additionally
// emits the JSON files + prints the seed metadata SQL block to stdout.
//
// Output directory: `<projectRoot>/build/generated/symbol-pack-payloads/`.
//
// Manual upload follows (per ADR-016 §3.1, the bucket is private and
// payloads are mediated by the 41.1.5 Edge Function — no public-read
// path exists): use the Supabase Dashboard or `supabase storage cp` to
// place the files at the path matching the printed `payloadPath`. The
// printed seed SQL is then applied via `mcp__supabase__apply_migration`.
val generateSymbolPackPayloads by tasks.registering(Test::class) {
    description =
        "Regenerates seed symbol pack payload.json files + prints metadata SQL for upload."
    group = "skeinly content authoring"

    val testTaskProvider = tasks.named("testAndroidHostTest", Test::class)
    testClassesDirs = testTaskProvider.get().testClassesDirs
    classpath = testTaskProvider.get().classpath
    dependsOn("compileAndroidHostTest")

    filter {
        includeTestsMatching(
            "io.github.b150005.skeinly.tools.SymbolPackPayloadGeneratorTest.generatePayloadsAndSeedSql",
        )
    }
    systemProperty(
        "skeinly.payloads.outputDir",
        layout.buildDirectory
            .dir("generated/symbol-pack-payloads")
            .get()
            .asFile.absolutePath,
    )

    // Always re-run when invoked — the test side effect is the JSON file
    // emission, not a Gradle output we can declare.
    outputs.upToDateWhen { false }

    // Forward the test's stdout to the Gradle console so the manifest +
    // seed SQL block surface to the dev directly without digging into
    // build/reports/tests/.
    testLogging {
        showStandardStreams = true
        events("passed", "failed", "skipped")
    }
}
